exclude:
    - ".idea"
timezone: "Europe/Tallinn"
title: "LAPhack 2021"
description: "Either it is a big or a small idea, Laphack is the place where You can meet magnificent people, who will give Your idea a shape, content and appearance.
"
